ASP.NET MVC/WebAppPM/WebAppPM/Controllers/ProjectController.cs
using CodeFirst;
using System;
using System.Data.Entity;
using System.Web.Mvc;

namespace WebAppPM.Controllers
{
    public class ProjectController : Controller
    {
        // Create data context
        SampleContext db = new SampleContext();
                
        public int MyProperty { get; set; }

        [HttpGet]
        public ActionResult UserProject(int? id)
        {
            var user = db.Users.Find(id);
            var projects = user.Projects;
            
            return View(projects);   
        }

        #region Add project

        [HttpGet]
        public ActionResult AddProject()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddProject(Project project)
        {
            // Assign user with Id = 2 to new project
            var user = db.Users.Find(2);

            user.Projects.Add(project);
            project.Users.Add(user);

            db.SaveChanges();

            return View();
        }

        #endregion

        #region Edit project

        [HttpGet]
        public ActionResult EditProject(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Project project = db.Projects.Find(id);
            if (project != null)
                return View(project);

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult EditProject(Project project)
        {
            db.Entry(project).State = EntityState.Modified;
            db.SaveChanges();
            return View();
        }

        #endregion

        #region Delete project

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        [HttpPost, ActionName("Delete")]
        public String DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return "Not found";
            }

            var user = db.Users.Find(2);

            db.Projects.Remove(project);
            user.Projects.Remove(project);
            
            db.SaveChanges();
            return "Project has been removed!";
        }

        #endregion
    }
}

ASP.NET MVC/WebAppPM/WebAppPM/Views/Project/AddProject.cshtml
@model CodeFirst.Project

@{
    ViewBag.Title = "AddProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddProject</h2>

@using (Html.BeginForm("AddProject", "Project", FormMethod.Post))
{
    <fieldset>
        <p>
            @Html.LabelFor(m => m.ProjectID, "Project Id")
            <br />
            @Html.EditorFor(m => m.ProjectID)
        </p>
        <p>
            @Html.LabelFor(m => m.ProjectName, "Project name")
            <br />
            @Html.EditorFor(m => m.ProjectName)
        </p>
        <p>
            @Html.LabelFor(m => m.Description, "Description")
            <br />
            @Html.EditorFor(m => m.Description)
        </p>

        <p><input type="submit" value="Add" /></p>
    </fieldset>
}

ASP.NET MVC/WebAppPM/WebAppPM/Views/Project/Delete.cshtml
@model CodeFirst.Project
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<dl>
    <dt>Project #@Model.ProjectID</dt>
    <dd>
        @Html.DisplayFor(model => model.ProjectName)
    </dd>

    <dt>Description</dt>
    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>
</dl>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

ASP.NET MVC/WebAppPM/WebAppPM/Views/Project/EditProject.cshtml
@model CodeFirst.Project
@{
    ViewBag.Title = "EditProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditProject</h2>

@using (Html.BeginForm("EditProject", "Project", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.ProjectID)

        <p>
            @Html.LabelFor(m => m.ProjectName, "Project name")
            <br />
            @Html.EditorFor(m => m.ProjectName)
        </p>
        <p>
            @Html.LabelFor(m => m.Description, "Description")
            <br />
            @Html.EditorFor(m => m.Description)
        </p>

        <p><input type="submit" value="Edit" /></p>
    </fieldset>
}

ASP.NET MVC/WebAppPM/WebAppPM/Views/Project/UserProject.cshtml
@model IEnumerable<CodeFirst.Project>
@{
    ViewBag.Title = "UserProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Projects of user</h2>

<div>
    <h3>Registered Users</h3>
    <table>
        <tr>
            <td><p>Project Name</p></td>
            <td><p>Description</p></td>
        </tr>
        @foreach (CodeFirst.Project p in Model)
            {
            <tr>
                <td><p>@p.ProjectName</p></td>
                <td><p>@p.Description</p></td>
            </tr>
        }
    </table>
</div>